### ISSUE TITLE
Teukolsky package does not load properly

### ISSUE THREAD

**Issue by bbonga** [BlackHolePerturbationToolkit/MathematicaToolkitExamples#1]
I tried to run the "Teukolsky.nb" example file, but not all the information in the Teukolsky package seems to load properly.
The functions from KerrGeodesics work fine. It loads the information for TeukolskyRadial and TeukolskyRadialFunction defined in the Teukolsky package, however, these functions don't work. The routines MSTRadialUp, MSTRadialIn, SasakiNakamuraRadialUp, etc. are not loaded all together.

Any help appreciated!

**Comment by nielsw2** [comment]
The example notebook has been updated to reflect the new API of the Teukolsky package (which has also been updated so the master branch has the most recent version).

Let us know if you have any issues or questions.

**Comment by bbonga** [comment]
Thanks Niels! It works like a charm now :)
